# Generated by Django 2.2.16 on 2022-09-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2022-09-04 06:00:00.000000-08:00', verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
