# Generated by Django 2.2.16 on 2022-09-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220908_1712'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title')},
        ),
    ]
