# Generated by Django 2.2.16 on 2022-09-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220908_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('year',)},
        ),
    ]
