# Generated by Django 2.2.16 on 2022-09-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_user_confirmation_code'),
        ('reviews', '0010_auto_20220909_2104'),
    ]

    operations = [
    ]
