# Generated by Django 2.2.16 on 2022-09-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220911_2236'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_title_review',
        ),
    ]
